In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('runs/20260626T225927527291Z-d3ra07733k/evaluation_metrics.csv')

In [3]:
df

,domain,field,precision,recall,f1,true_positive,predicted,expected,gold_rows,gold_doi,gold_path
0,seltox,access,0.875,1.000000,0.933333,7,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
1,seltox,article_list,0.000,0.000000,0.000000,0,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
2,seltox,bacteria,0.875,1.000000,0.933333,7,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
3,seltox,coating,0.000,0.000000,0.000000,0,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
4,seltox,concentration,0.875,1.000000,0.933333,7,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
5,seltox,concentration_of_precursor_mM,0.875,1.000000,0.933333,7,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
6,seltox,doi,0.875,1.000000,0.933333,7,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
7,seltox,duration_preparing_extract_min,0.875,1.000000,0.933333,7,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
8,seltox,hydrodynamic_diameter_nm,0.875,1.000000,0.933333,7,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
9,seltox,is_oa,0.875,1.000000,0.933333,7,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
10,seltox,journal_is_oa,0.875,1.000000,0.933333,7,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
11,seltox,journal_name,0.875,1.000000,0.933333,7,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
12,seltox,mdr,0.875,1.000000,0.933333,7,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
13,seltox,method,0.000,0.000000,0.000000,0,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
14,seltox,mic_np_µg_ml,0.875,1.000000,0.933333,7,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
15,seltox,np,0.000,0.000000,0.000000,0,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
16,seltox,np_size_avg_nm,0.875,1.000000,0.933333,7,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
17,seltox,np_size_max_nm,0.000,0.000000,0.000000,0,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
18,seltox,np_size_min_nm,0.000,0.000000,0.000000,0,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
19,seltox,np_synthesis,0.000,0.000000,0.000000,0,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
20,seltox,oa_status,0.875,1.000000,0.933333,7,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
21,seltox,pdf,0.000,0.000000,0.000000,0,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
22,seltox,ph_during_synthesis,0.000,0.000000,0.000000,0,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
23,seltox,precursor_of_np,0.875,1.000000,0.933333,7,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
24,seltox,publisher,0.000,0.000000,0.000000,0,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
25,seltox,reference,0.000,0.000000,0.000000,0,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
26,seltox,shape,0.875,1.000000,0.933333,7,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
27,seltox,sn,0.000,0.000000,0.000000,0,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
28,seltox,solvent_for_extract,0.000,0.000000,0.000000,0,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
29,seltox,strain,0.625,0.714286,0.666667,5,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
30,seltox,temperature_for_extract_C,0.875,1.000000,0.933333,7,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
31,seltox,time_set_hours,0.000,0.000000,0.000000,0,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
32,seltox,title,0.875,1.000000,0.933333,7,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
33,seltox,year,0.875,1.000000,0.933333,7,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
34,seltox,zeta_potential_mV,0.625,0.714286,0.666667,5,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...
35,seltox,zoi_np_mm,0.875,1.000000,0.933333,7,8,7,7,10.1039/d3ra07733k,/home/dokoo-lua/CheML/datasets/NANOMATERIALS/S...

In [4]:
df2 = pd.read_csv('runs/20260626T225927527291Z-d3ra07733k/prediction.csv')

In [5]:
df2

,sn,np,coating,bacteria,mdr,strain,np_synthesis,method,mic_np_µg_ml,concentration,...,article_list,journal_name,publisher,year,title,journal_is_oa,is_oa,oa_status,pdf,access
0,1,AgNP@Fo,1,Pseudomonas aeruginosa,0,CCT 1476,aqueous secretome of Fusarium oxysporum f. sp....,96-well microplate dilution technique,0.84,NaN,...,NaN,RSC Advances,Royal Society of Chemistry,2024,Biogenic silver nanoparticles' antibacterial a...,True,True,gold,d3ra07733k.pdf,1
1,2,AgNP@OR,1,Pseudomonas aeruginosa,0,CCT 1476,orange peel extract,96-well microplate dilution technique,27.00,NaN,...,NaN,RSC Advances,Royal Society of Chemistry,2024,Biogenic silver nanoparticles' antibacterial a...,True,True,gold,d3ra07733k.pdf,1
2,3,AgNP@Fo,1,Staphylococcus aureus,0,CCT1485,aqueous secretome of Fusarium oxysporum f. sp....,96-well microplate dilution technique,1.68,NaN,...,NaN,RSC Advances,Royal Society of Chemistry,2024,Biogenic silver nanoparticles' antibacterial a...,True,True,gold,d3ra07733k.pdf,1
3,4,AgNP@OR,1,Staphylococcus aureus,0,CCT1485,orange peel extract,96-well microplate dilution technique,NaN,NaN,...,NaN,RSC Advances,Royal Society of Chemistry,2024,Biogenic silver nanoparticles' antibacterial a...,True,True,gold,d3ra07733k.pdf,1
4,5,AgNP@Fo,1,Escherichia coli,0,CCT1457,aqueous secretome of Fusarium oxysporum f. sp....,96-well microplate dilution technique,0.84,NaN,...,NaN,RSC Advances,Royal Society of Chemistry,2024,Biogenic silver nanoparticles' antibacterial a...,True,True,gold,d3ra07733k.pdf,1
5,6,AgNP@OR,1,Escherichia coli,0,CCT1457,orange peel extract,96-well microplate dilution technique,27.00,NaN,...,NaN,RSC Advances,Royal Society of Chemistry,2024,Biogenic silver nanoparticles' antibacterial a...,True,True,gold,d3ra07733k.pdf,1
6,7,AgNP@Fo,1,Enterococcus faecalis,0,CCT 1494,aqueous secretome of Fusarium oxysporum f. sp....,96-well microplate dilution technique,1.68,NaN,...,NaN,RSC Advances,Royal Society of Chemistry,2024,Biogenic silver nanoparticles' antibacterial a...,True,True,gold,d3ra07733k.pdf,1
7,8,AgNP@OR,1,Enterococcus faecalis,0,CCT 1494,orange peel extract,96-well microplate dilution technique,10.80,NaN,...,NaN,RSC Advances,Royal Society of Chemistry,2024,Biogenic silver nanoparticles' antibacterial a...,True,True,gold,d3ra07733k.pdf,1